# Stage-2 framework constraints. Board-specific PL clock is generated by PS.
# Add external FAST ingress pins/GT constraints when the network front-end is selected.
set_false_path -from [get_pins -hierarchical -quiet *quant_stream_mux_0*] -to [get_pins -hierarchical -quiet *quant_stream_mux_0*]
