# DPD clock-domain constraints.
#
# RFDAC1_CLK is generated by the RFDC sample-clock tree while clk_pl_0 is the
# PS/PL AXI control clock.  They have no common primary clock and must not be
# timed against one another.  RTL crossings use XPM asynchronous FIFOs,
# independent-clock block RAMs, or explicitly marked synchronizers.

set_clock_groups -asynchronous \
    -group [get_clocks RFDAC1_CLK] \
    -group [get_clocks clk_pl_0]
